services:

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: traffic
      POSTGRES_PASSWORD: traffic
      POSTGRES_DB: trafficdb
      TZ: Asia/Kolkata
    ports:
      - "5432:5432"

  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"