KAFKA_BOOTSTRAP_SERVERS = "localhost:9092"

INPUT_STREAM = "tracked_objects"
PLATE_CACHE_TOPIC = "vehicle_plate_cache"

TRACK_TTL = 30
MAX_TRACK_HISTORY = 20
PLATE_MIN_SPEED = 2
PLATE_MIN_WIDTH = 120
PLATE_MIN_HEIGHT = 60
PLATE_REQUEST_TTL = 2

POSTGRES_HOST = "localhost"
POSTGRES_PORT = 5432
POSTGRES_DB = "trafficdb1"
POSTGRES_USER = "traffic1"
POSTGRES_PASSWORD = "traffic1"
